FROM alpine:3.18

RUN apk add --no-cache \
    python3 \
    build-base \
    make \
    meson \
    gcc \
    g++ \
    gdb \
    clang \
    clang-extra-tools \
    ninja \
    cmake \
    pkgconfig \
    musl-dev \
    libc-dev \
    avr-libc \
    valgrind \
    tzdata \
    git \
    inih

RUN apk add --no-cache \
    bash-completion \
    inih-dev